### ISSUE TITLE
Does this only do Facebook

### ISSUE THREAD

**Issue by ceased-ebc** [mheinl/OnionCrawler#1]
Hi noticed the DB filling up with FB related (recipes) many gigs worth, but can not see any actual extracted content, only fb links, so question is, is it only scraping FB related pages (which are giving errors 
![screen shot 2017-07-25 at 18 27 13](https://user-images.githubusercontent.com/7057144/28585058-ed8f2560-7166-11e7-8a49-cd79d9cc92be.png)

**Comment by mheinl** [comment]
Hi,
Thanks for asking. No, it's not only doing Facebook. However, it uses Facebook's hidden service (https://facebookcorewwwi.onion/) as it's default input URL. You can easily change that using the corresponding CLI parameter described in the readme. Just add " -a inputURL=https://whereeverYouWannaStartCrawlingFrom.onion" when you run OnionCrawler. Another possible solution is to use a list of .onion URLs (parameter " -a inputOnionList=thisIsYourList.txt") or a logfile of the MEMEX tool HSProbe (" -a inputHSProbeLog=thisIsYourHSProbe.log").

I hope this helps. If you have any further questons, do not hesitate to contact me again.

Regards,
Mike
