### ISSUE TITLE
cant edit torsock.conf

### ISSUE THREAD

**Issue by shiv1233333** [mheinl/OnionCrawler#2]
hi Mike

im attempting to run the crawler via postgres however im encountering an issue when attemping to uncomment the "allowoutboundloccalhost". when I attempt to do this is get a permisson denied error and was wondering if you had a work around? If it helps im running this on Ubuntu 

thank you

**Comment by mheinl** [comment]
Hi,
Sorry for the delayed response. Setting up an instance of the most recent Ubuntu and installing everything from scratch, I couldn't reproduce your error. Have you employed the 'sudo' command when editing /etc/tor/torsocks.conf?
