### ISSUE TITLE
File system

### ISSUE THREAD

**Issue by shiv1233333** [mheinl/OnionCrawler#3]
Hii, 
Thank you for your help earlier, I'm completely new to python and web scraping and was hoping you might give me a better understanding of how the url gets placed into a file. I understand that it uses the pipelines but don't exactly understand how these urls get written in the file. 

Thank you very much for your help

**Comment by mheinl** [comment]
Hi,
Thanks for your patience. You can either collect them and put them into the file manually or you use the OnionHarvester script located in my repository as well: https://github.com/mheinl/onion_harvester.py

With OnionHarvester you can systematically harvest .onion addresses from Google.

Hope this helps. If you have any further questions, please do not hesitate to contact me.
